apiVersion: apps/v1
kind: Deployment
metadata:
  name: moog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moog
  template:
    metadata:
      labels:
        app: moog
    spec:
      containers:
        - name: moog
          image: inseefr/moog:2.0.4
          env:
            - name: DATACOLLECTION_MANAGEMENT_API
              value: "https://datacollection-management-api.dev.insee.io/moog"

