name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: yarn --frozen-lockfile
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: yarn
      - run: yarn run test
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
